#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-heroku-api
Version  : 0.3.23
Release  : 1
URL      : https://rubygems.org/downloads/heroku-api-0.3.23.gem
Source0  : https://rubygems.org/downloads/heroku-api-0.3.23.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-excon
BuildRequires : rubygem-minitest
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
Heroku Ruby Client
==================
The Heroku Ruby Client is used to interact with the [Heroku Legacy API](http://legacy-api-docs.herokuapp.com) from Ruby.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n heroku-api-0.3.23
gem spec %{SOURCE0} -l --ruby > rubygem-heroku-api.gemspec

%build
gem build rubygem-heroku-api.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
heroku-api-0.3.23.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/heroku-api-0.3.23
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/heroku-api-0.3.23.gem
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/ErrorWithResponse/cdesc-ErrorWithResponse.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/ErrorWithResponse/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/ErrorWithResponse/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/Forbidden/cdesc-Forbidden.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/Locked/cdesc-Locked.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/NilApp/cdesc-NilApp.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/NotFound/cdesc-NotFound.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/RateLimitExceeded/cdesc-RateLimitExceeded.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/RequestFailed/cdesc-RequestFailed.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/Timeout/cdesc-Timeout.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/Unauthorized/cdesc-Unauthorized.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/VerificationRequired/cdesc-VerificationRequired.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/Marshal/cdesc-Marshal.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/add_mock_app_addon-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/add_mock_release-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/cdesc-Mock.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_addon-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_addon_price-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_app-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_app_addon-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_app_domain-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_collaborator-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_feature-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_key-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/get_mock_processes-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/parse_stub_params-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/remove_mock_app_addon-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/timestamp-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/unescape-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/Mock/with_mock_app-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/addon_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/app_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/cdesc-API.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/decompress_response%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_addon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_collaborator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_config_var-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_domains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_feature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/delete_ssl_endpoint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/escape-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_addons-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_app_maintenance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_apps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_attachments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_collaborators-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_config_vars-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_domains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_dyno_types-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_feature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_features-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_keys-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_logs-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_ps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_releases-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_ssl_endpoint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_ssl_endpoints-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_stack-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/get_user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_addon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_app_maintenance-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_collaborator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_feature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_login-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ps_restart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ps_scale-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ps_stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_release-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ssl_endpoint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/post_ssl_endpoint_rollback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/ps_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_addon-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_app-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_config_vars-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_dynos-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_formation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_ssl_endpoint-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_stack-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/put_workers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/API/second_factor-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/Heroku/cdesc-Heroku.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/lib/heroku/api/mock/cache/page-get_addons_json.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/lib/heroku/api/mock/cache/page-get_features_json.ri
/usr/lib64/ruby/gems/2.2.0/doc/heroku-api-0.3.23/ri/lib/heroku/api/mock/cache/page-get_user_json.ri
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/README.md
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/changelog.txt
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/heroku-api.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku-api.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/addons.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/apps.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/attachments.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/collaborators.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/config_vars.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/domains.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/features.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/login.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/logs.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/addons.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/apps.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/attachments.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/cache/get_addons.json
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/cache/get_features.json
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/cache/get_user.json
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/collaborators.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/config_vars.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/domains.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/features.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/login.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/logs.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/processes.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/releases.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/stacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/mock/user.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/processes.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/releases.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/ssl_endpoints.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/stacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/user.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/lib/heroku/api/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/data/site.crt
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/data/site.key
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_addons.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_apps.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_attachments.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_collaborators.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_config_vars.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_domains.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_error_conditions.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_features.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_keys.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_login.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_logs.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_processes.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_releases.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_second_factor.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_ssl_endpoints.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_stacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/heroku-api-0.3.23/test/test_user.rb
/usr/lib64/ruby/gems/2.2.0/specifications/heroku-api-0.3.23.gemspec
