#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-heroku-api
Version  : 0.4.2
Release  : 5
URL      : https://rubygems.org/downloads/heroku-api-0.4.2.gem
Source0  : https://rubygems.org/downloads/heroku-api-0.4.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-excon
BuildRequires : rubygem-minitest
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
Heroku Ruby Client
==================
The Heroku Ruby Client is used to interact with the [Heroku Legacy API](http://legacy-api-docs.herokuapp.com) from Ruby.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n heroku-api-0.4.2
gem spec %{SOURCE0} -l --ruby > rubygem-heroku-api.gemspec

%build
export LANG=C
gem build rubygem-heroku-api.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
heroku-api-0.4.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/heroku-api-0.4.2
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/heroku-api-0.4.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/changelog.txt
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/heroku-api.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku-api.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/addons.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/apps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/attachments.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/buildpacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/collaborators.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/config_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/domains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/login.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/logs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/addons.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/apps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/attachments.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/buildpacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/cache/get_addons.json
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/cache/get_features.json
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/cache/get_user.json
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/collaborators.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/config_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/domains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/features.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/login.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/logs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/processes.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/releases.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/stacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/mock/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/processes.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/releases.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/ssl_endpoints.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/stacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/lib/heroku/api/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/data/site.crt
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/data/site.key
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_addons.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_api.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_apps.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_attachments.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_buildpacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_collaborators.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_config_vars.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_domains.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_error_conditions.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_features.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_keys.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_login.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_logs.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_processes.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_releases.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_second_factor.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_ssl_endpoints.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_stacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/heroku-api-0.4.2/test/test_user.rb
/usr/lib64/ruby/gems/2.3.0/specifications/heroku-api-0.4.2.gemspec
